# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Namal Teaching
tagline:          'Namal Teaching - Courses- syllabus '
description:      'OOP-CS, EE-PF'
#url:              http://127.0.0.1:4000/
#baseurl:          http://127.0.0.1:4000

author:
  name:           'Gul Aftab'
  url:            http://127.0.0.1:4000

include: ["_pages"]

paginate:         5

# Custom vars
version:          Session 2017-18

github:
  repo:           https://github.com/gulahmed
